site_name: MedGraph
nav: 
  - Home: index.md
  - Project:
    - Architecture: arc.md
  - Data:
    - Census: data/census.md
    - SNOMED: data/snomed.md
    - FAERS: data/faers.md
  - Graphs: graph.md
  - 'Data Visualisation': visual.md
theme: 
  name: material