site_name: My Docs
nav: 
  - Home: index.md
  - Projects:
    - Architecture: arc.md
  - Data:
    - Census: census.md
    - SNOMED: snomed.md
    - FAERS: faers.md
  - Graph: graph.md
  - 'Data Visualisation': visual.md
theme: 
  name: material